# Generated by Django 5.1.4 on 2025-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fa_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
