# Generated by Django 5.1.4 on 2025-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_fa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_present',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
