# Generated by Django 5.1.4 on 2025-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='qr/files'),
        ),
    ]
