# Generated by Django 5.1.4 on 2025-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_qrcode_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
